FROM php:7.3.10-cli

RUN apt-get update \
    && apt-get install -y \
    git zip libcurl4-openssl-dev libssl-dev pkg-config

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install the gmp
RUN apt-get update -y && \
    apt-get install -y libgmp-dev re2c libmhash-dev file && \
    ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/ && \
    docker-php-ext-configure gmp && \
    docker-php-ext-install gmp

COPY . /var/www/html/
WORKDIR /var/www/html
RUN composer install

# Use the official PHP 7.3 image.
# https://hub.docker.com/_/php
FROM php:7.3-apache
RUN a2enmod rewrite
RUN a2enmod headers

# Copy local code to the container image.
COPY . /var/www/html/
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 777 /var/www/html/storage
COPY --from=0 /var/www/html/vendor /var/www/html/vendor

# Use the PORT environment variable in Apache configuration files.
RUN sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Configure PHP for development.
# Switch to the production php.ini for production operations.
# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
# https://hub.docker.com/_/php#configuration
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

ENV GOOGLE_APPLICATION_CREDENTIALS /var/www/html/GOOGLE_APPLICATION_CREDENTIALS.json

# Install GCloud
RUN apt-get update -y && apt-get install -y gnupg2
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
RUN gcloud auth activate-service-account --key-file=/var/www/html/GOOGLE_APPLICATION_CREDENTIALS.json
RUN gcloud auth print-identity-token
RUN usermod -a -G root www-data
