openapi: 3.0.0
info:
  title: Wallet Gateway Service
  version: 0.0.1
  description: |
    The Wallet Gateway API is a REST HTTP API for Creating digital wallets. There are different components involved in digital wallet operations

    # Wallet Plans
    A wallet plan is used to group common characteristics of a set of wallet accounts. For example, the default currency to use or the balance threshold allowed
    for the associed accounts

    # Wallet Organizations
    Each legal authority that uses our wallet gateway needs to be linked with a wallet organization. It could be a company or any type of organizations. That is where
    KYB or legal documents operations take place

    # Wallet Accounts
    An account is what represents user interactions with our gateway

    # Wallet Account Users
    User personal information are handled separately from their acconuts. So we can apply specific security constraints


  termsOfService: 'http://swagger.io/terms/'
  x-logo:
    url: 'https://redocly.github.io/redoc/petstore-logo.png'
    backgroundColor: '#FFFFFF'
    altText: Petstore logo
servers:
  - url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
    description: Testing Server
  - url: 'https://sandbox.wallet-gateway-svc.nkeita-serives.com'
    description: Sandbox Server
  - url: 'https://sandbox.wallet-gateway-svc.nkeita-serives.com'
    description: Production Server
tags:
  - name: Wallet Plans
    description: Wallet Plans are used to group wallet accounts that have common characteristics
    externalDocs:
      url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
  - name: Wallet Organizations
    description: A Wallet Organization is a company that have a set of wallet plans
    externalDocs:
      url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
  - name: Wallet Accounts
    description: Wallet accounts
    externalDocs:
      url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
  - name: Wallet Account Users
    description: Wallet account owners
    externalDocs:
      url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
paths:
  /v1/wallets/plans:
    $ref: 'open-api-wallet-plans-spec.yaml'
  /v1/wallets/plans/{planId}:
    $ref: 'open-api-wallet-plan-spec.yaml'
  /v1/wallets/organizations:
    $ref: 'open-api-wallet-organizations-spec.yaml'
  /v1/wallets/organizations/{organizationId}:
    $ref: 'open-api-wallet-organization-spec.yaml'
  /v1/wallets/accounts:
    $ref: 'open-api-wallet-accounts-spec.yaml'
  /v1/wallets/accounts/{accountId}:
    $ref: 'open-api-wallet-account-spec.yaml'
  /v1/wallets/accounts/users:
    $ref: 'open-api-wallet-account-users-spec.yaml'
components:
  schemas:
    WalletPlan:
      type: object
      properties:
        currency:
          $ref: '#/components/schemas/Currency'
        status:
          $ref: '#/components/schemas/WalletPlanStatus'
    WalletPlans:
      items:
        $ref: '#/components/schemas/WalletPlan'
    WalletPlanStatus:
      type: string
      description: Actual Status of the wallet plan
      enum:
        - active
        - deactivated
    Currency:
      type: string
      enum:
        - EUR
        - GPB
    WalletOrganization:
      type: object
      properties:
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    WalletOrganizations:
      type: array
      items:
        $ref: '#/components/schemas/WalletOrganization'
    Address:
      type: object
      properties:
        streetName:
          type: string
          description: The street name
          example: voie de seine
        streetNumber:
          type: string
          description: The street number
          example: 3
        city:
          type: string
          description: The city name
          example: paris
        zipCode:
          type: string
          description: The zip code
          example: 75017
        state:
          type: string
          description: The state name
          example: France
        country:
          type: string
          description: The country name
    WalletAccount:
      type: object
      properties:
        id:
          type: string
          description: A wallet account identifier provided during this account creation
          example: 96808ac6-fa7e-4a88-be30-52c3533f4a47
        walletPlanId:
          type: string
          description: The Wallet Platform identifier for the wallet plan this accountrefers to
        accountType:
          type: string
          description: A master account that's linked to an organization or a regular account used by organization customers
          enum:
            - master
            - regular
        balance:
          type: number
          description: The actual balance of this account
        name:
          type: string
          description: A name that identifies this account
        address:
          $ref: '#/components/schemas/Address'
    WalletAccounts:
      type: array
      items:
        $ref: '#/components/schemas/WalletAccount'
    WalletAccountUser:
      type: object
      properties:
        id:
          type: string
          description: An identifier that represents the user in the Wallet Platform
          example: 5e4203f3-c949-4e66-a732-9eaa803a3a66
        lastName:
          type: string
          description: User last name
        firstName:
          type: string
          description: User first name
        address:
          $ref: '#/components/schemas/Address'
          description: User address
        email:
          type: string
          description: user email address
        phoneNumber:
          type: string
          description: User phone number
          example: '+33613047943'
    WalletAccountUsers:
      type: array
      items:
        $ref: '#/components/schemas/WalletAccountUser'
